### ISSUE TITLE
replicate implementation.

### ISSUE THREAD

**Issue by MariasStory** [wyhuai/DDNM#1]
Dear authors,
Thank you very much for the interesting solution and publication.
Do you plan to put your solution on https://replicate.com/
Thank you

**Comment by wyhuai** [comment]
> 

Thanks for your suggestion， but our recent energy may be mainly focused on follow-up work, and we will consider further promotion when we have time.

**Comment by wyhuai** [comment]
> Dear authors, Thank you very much for the interesting solution and publication. Do you plan to put your solution on https://replicate.com/ Thank you

Thanks for your suggestion， but our recent energy may be mainly focused on follow-up work, and we will consider further promotion when we have time.
