### ISSUE TITLE
difference between main files

### ISSUE THREAD

**Issue by JunMa11** [wyhuai/DDNM#10]
Hi @wyhuai , 

Thanks for sharing the great work.

What's the difference between the following two main files? I know the 2nd one is scalable to different image sizes. Is the 2nd one always better than the 1st one in terms of performance?

https://github.com/wyhuai/DDNM/blob/main/main.py

https://github.com/wyhuai/DDNM/blob/main/hq_demo/main.py

**Comment by wyhuai** [comment]
The 1st one is for reproducing the **quantitative evaluation** in our paper.
The 2nd one is for reproducing the **high-quality results** presented in our paper, and we also added functions to support arbitrary sizes.
Usually, the 2nd one yields much better results than the 1st one when using longer time-travel parameters.

**Comment by JunMa11** [comment]
Hi @wyhuai ,

Thanks for your explanation very much.

For the denoising task, is there any way to automatically estimate the noise level `sigma_y`?
This is because in real-world settings, we do not know the true noise level.

**Comment by JunMa11** [comment]
A minor suggestion

The current code assumes that the model was trained by learning variance. 

https://github.com/wyhuai/DDNM/blob/1dd107a87563a748010cd831b977fe87b54210a9/hq_demo/guided_diffusion/gaussian_diffusion.py#L277


However, users may train the model without learning the variance. I would recommend including the original if-else statement.

https://github.com/openai/guided-diffusion/blob/22e0df8183507e13a7813f8d38d51b072ca1e67c/guided_diffusion/gaussian_diffusion.py#L262-L292
