### ISSUE TITLE
Is hq_demo better to apply custom model?

### ISSUE THREAD

**Issue by Changesong** [wyhuai/DDNM#14]
First, thank you for the great project. The mathematical processing is very interesting and wonderful.

Recently, I am studying image inpainting with Stable Diffusion 2. As far as I understand, since this project uses linear algebra, I think it will work regardless of the model structure if it is a diffusion model.
I've tried to apply it myself, but the size of the model and the structure of the yaml file are so different that it is difficult to apply it.

Then I found the hq_demo folder and the code looks cleaner there. Do you recommend applying custom model over hq_demo?

I am not an English speaker, so English may be awkward. I kindly ask for your understanding.

**Comment by wyhuai** [comment]
Hi, thanks for your attention,

I think DDNM can be easily applied to diffusion models operating in the image domain, e.g., Imagen, and Imagen Video. But for Stable Diffusion which operates on latent space, DDNM may not work.

To apply DDNM to your own models, you may refer to the "Applying DDNM to Your Own Diffusion Model" part in README.

**Comment by Changesong** [comment]
Thank you for your answer. As you said, image space and Latent space are definitely different. I overlooked that.

I'm curious about how it will work in the latent space, so I'll keep trying anyway.

Thank you again for your reply.

**Comment by lhaippp** [comment]
@Changesong Hi Change, didi you try to implement DDNM on Stable Diffusion? I'm also curious about it.

**Comment by Changesong** [comment]
@lhaippp When I tried it naively, it didn't seem to work.
After that, I realized that I could get the performance I needed without using DDNM, so I didn't proceed.

**Comment by lhaippp** [comment]
@Changesong OK cool, according to your comments, I'll have a try to utilize DDNM on pretrained imagen model.
