### ISSUE TITLE
Deblurring with a more complicated blur kernel

### ISSUE THREAD

**Issue by hamadichihaoui** [wyhuai/DDNM#15]
Hi, first thanks for your great work!

I was wondering if it is possible to apply your method to a more sophisticated kernel, a **random** 21x21 kernel for example.
I don't understand how you link the blur kernel to the SVD decomposition (basically how you define  A_small1 and A_small2 in Deblurring2D). Could you point to some literature that explain the derivation? and maybe how you think the random kernel case can be handled?

Thanks.

**Comment by vvictoryuki** [comment]
@hamadichihaoui Thanks for your question! For symmetric two-dimensional kernels, we can decompose them into one-dimensional sub-kernels in horizontal and vertical directions, corresponding to multiplying the sub-kernels on the left and right of the original image. If we want to do SVD decomposition for this deblurring degradation, we can do SVD decomposition for the left and right sub-kernels, respectively. This technique is mainly used to decrease computational costs. This method is not applicable if the considered two-dimensional kernel is random.

**Comment by wyhuai** [comment]
Hi, for random kernels, you may use the Fourier Transforms to calculate the pseudo inverse. You can refer to this paper and its repository: https://github.com/YuvalBahat/Explorable-Super-Resolution
