### ISSUE TITLE
How to find the tool mentioned by README to handle images?

### ISSUE THREAD

**Issue by chandelures** [wyhuai/DDNM#16]
First, thanks a lot for your nice work!

Now i need restore my own images , The document metions that we can use some tools to crap the images or draw a mask, but the link is broken, how can i find them?

> * If your are using CelebA pretrained models, try this [tool](https://github.com/wyhuai/DDNM/blob/main/???) to crop and align your photo.
> * If there are local artifacts on your photo, try this [tool](https://github.com/wyhuai/DDNM/blob/main/???) to draw a mask to cover them, and save this mask to DDNM/exp/inp_masks/mask.png. Then run DDNM/exp/inp_masks/get_mask.py to generate mask.npy.

**Comment by wyhuai** [comment]
Thanks for your reminder! you may use the [Colab of LAMA](https://colab.research.google.com/github/advimman/lama/blob/master/colab/LaMa_inpainting.ipynb#scrollTo=-VZWySTMeGDM) to draw a mask.

**Comment by chandelures** [comment]
Thanks for reply!
