### ISSUE TITLE
Applying to images>256

### ISSUE THREAD

**Issue by remybonnav** [wyhuai/DDNM#18]
Thanks for this great new work.

Is there a way to adapt this to images >256 pixels size? Like using tiles or mosaic?

**Comment by wyhuai** [comment]
Yes, the method for arbitrary size is presented in this [paper](https://arxiv.org/abs/2303.00354), and our [Colab](https://colab.research.google.com/drive/1SRSD6GXGqU0eO2CoTNY-2WykB9qRZHJv?usp=sharing) provides examples.
