### ISSUE TITLE
The link to download the SDEdit weights seems to have expired

### ISSUE THREAD

**Issue by yangzhao1230** [wyhuai/DDNM#34]
Hi,

Thanks for you interesting and great work! 

The link to download the SDEdit weights seems to have expired: https://github.com/ermongroup/SDEdit/issues/18. It appears that the SDEdit repository has not been updated for quite some time. Could you please provide a new link to download the weights?

**Comment by wyhuai** [comment]
Hi, we have updated the link.

**Comment by yangzhao1230** [comment]
Thanks for your quick response. But it seems that you only delete the link, I wonder how I can get the pretrained models?

**Comment by wyhuai** [comment]
We have uploaded the model to google drive, you can click the 'model' for the link, or, here

https://drive.google.com/file/d/1wSoA5fm_d6JBZk4RZ1SzWLMgev4WqH21/view?usp=share_link
