### ISSUE TITLE
About formula derivation x_hat and x_bar

### ISSUE THREAD

**Issue by chensming** [wyhuai/DDNM#38]
Hi, bro, a nice work! But I am not very understanding of a problem. 
In the section "2.2 RANGE-NULL SPACE DECOMPOSITION", I have seen this equation
![image](https://github.com/wyhuai/DDNM/assets/45591767/701f9d6b-42f1-4e71-b2cc-e90a0dad137e)

And in "3.1 DENOISING DIFFUSION NULL-SPACE MODEL", in this context, 
![image](https://github.com/wyhuai/DDNM/assets/45591767/237b07d5-4241-43e0-9183-d1908d95d50b)
I don't understand the difference between $\hat{x}$ and $\bar{x}$
![image](https://github.com/wyhuai/DDNM/assets/45591767/b18bdfc8-c5b1-47df-8050-d28ac34ff3a9)
and here the $y=Ax$?

**Comment by wyhuai** [comment]
Hi, thanks for your attention!

Yes, $y=Ax$, $\hat{x}$ is our final solution, and $\bar{x}$ is the only unknown variable that needs to be solved.

**Comment by chensming** [comment]
> 

Oh, thanks. And I would like to know if you have tried some non-linear recovery tasks such as rain removal, fog removal and light enhancement. Do you have some suggestions for that?

**Comment by wyhuai** [comment]
The difficulty of rain removal is difficult since the degradation A is unknown and is hard to predict. I guess you may refer to recent supervised methods for such degradation-agnostic problems.

**Comment by chensming** [comment]
> Tasks like rain removal are difficult since the degradation A is unknown and is hard to predict. I guess you may refer to recent supervised methods for such degradation-agnostic problems.

Oh. I have another problem, here I don't know how to get this equation:
![image](https://github.com/wyhuai/DDNM/assets/45591767/1315fe94-d90e-4744-a574-119d6d6fedc6)

The context of it is as followings:
![image](https://github.com/wyhuai/DDNM/assets/45591767/3e6cbae5-28f0-4f03-a1a5-d966fbd53797)

**Comment by wyhuai** [comment]
For this equation, the left side is our variance, the right side is the originally defined variance. Note that this equation is a simplified one, inaccurate. You may also refer to the appendix of [Unlimited-Size Diffusion Restoration](https://scholar.google.com/citations?view_op=view_citation&hl=zh-CN&user=Ltv5xvcAAAAJ&citation_for_view=Ltv5xvcAAAAJ:zYLM7Y9cAGgC) for accurate calculation of the variance calculation.

**Comment by chensming** [comment]
> For this equation, the left side is our variance, the right side is the originally defined variance. Note that this equation is a simplified one, inaccurate. You may also refer to the appendix of [Unlimited-Size Diffusion Restoration](https://scholar.google.com/citations?view_op=view_citation&hl=zh-CN&user=Ltv5xvcAAAAJ&citation_for_view=Ltv5xvcAAAAJ:zYLM7Y9cAGgC) for accurate calculation of the variance calculation.

Oh, thanks! You are so kind! Hope to see you on campus someday. ^_^
