### ISSUE TITLE
About PSNR metrics

### ISSUE THREAD

**Issue by chensming** [wyhuai/DDNM#42]
Hi, bro. Nice to see you. When I evaluate the metrics output image, I find that the PSNR you implement is different from the code implemented by torchmetrics.

Here is your version:
https://github.com/wyhuai/DDNM/blob/3d8cd1aa81eb3c218351ba4e5ac5389fe6aca7c2/guided_diffusion/diffusion.py#L406
```python
 mse = torch.mean((x[0].to(self.device) - orig) ** 2)
 psnr = 10 * torch.log10(1 / mse)
```
<br>

But the torchmetrics is 
```python
mse = torch.mean((x[0].to(self.device) - orig) ** 2)
psnr = 10 * torch.log10(torch.max(orig)**2 / mse)
```
<br>

so when I use the api implemented by torchmetrics to calculate the psnr of output image 
```python
from torchmetrics import PeakSignalNoiseRatio
psnr_calculator = PeakSignalNoiseRatio()
psnr_calculator(x[0], orig.cpu())
```

They will lead to different output. For example, when I run this script
```bash
python main.py --ni --simplified --config imagenet_256.yml --path_y imagenet --eta 0.85 --deg "sr_averagepooling" --deg_scale 4.0 --sigma_y 0.1 -i demo
```
The output by torchmetrics is 30.3245, and yours is 30.3587. Although they are close, I want to know if it's important.

![image](https://github.com/wyhuai/DDNM/assets/45591767/0256e091-98df-47da-8223-14007162a268)

**Comment by wyhuai** [comment]
I think they are both acceptable, as long as the same calculation is applied to all compared methods (fair comparison).

**Comment by chensming** [comment]
> I think they are both acceptable, as long as the same calculation is applied to all compared methods (fair comparison).

Ok Thanks~
