### ISSUE TITLE
Download link not working

### ISSUE THREAD

**Issue by zz1plu** [wyhuai/DDNM#44]
Hi， the Download link 'https://image-editing-test-12345.s3-us-west-2.amazonaws.com/checkpoints/celeba_hq.ckpt' can't work. It is in File "DDNM/guided_diffusion/diffusion.py", line 134 . 
I open the URL, and it shows：
> This XML file does not appear to have any style information associated with it. The document tree is shown below.
> <Error>
> <Code>AccessDenied</Code>
> <Message>Access Denied</Message>
> <RequestId>RJY67AGA9CASHPB4</RequestId>
> <HostId>k/v9atKLGKrKfqeC7bKJKzqE9Y4Mrt1LZCqYQuNHH4OphxuSg0FLNuO/LTMs6bGmHf1aH961B7uHDKnirAmWLQ==</HostId>
> </Error>

And When I enter the command
`python main.py --ni --simplified --config celeba_hq.yml --path_y celeba_hq --eta 0.85 --deg "sr_averagepooling" --deg_scale 4.0 --sigma_y 0 -i demo`
an error occurs as follows：
> INFO - main.py - 2023-05-31 11:21:07,706 - Using device: cuda
> 1.02kB [00:00, 1.57MB/s]
> ERROR - main.py - 2023-05-31 11:21:11,007 - Traceback (most recent call last):
>   File "/DDNM/main.py", line 166, in main
>     runner.sample(args.simplified)
>   File "/DDNM/guided_diffusion/diffusion.py", line 138, in sample
>     model.load_state_dict(torch.load(ckpt, map_location=self.device))
>   File "/anaconda3/envs/ddnm/lib/python3.9/site-packages/torch/serialization.py", line 595, in load
>     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
>   File "/anaconda3/envs/ddnm/lib/python3.9/site-packages/torch/serialization.py", line 764, in _legacy_load
>     magic_number = pickle_module.load(f, **pickle_load_args)
> _pickle.UnpicklingError: invalid load key, '<'.

**Comment by wyhuai** [comment]
try this link:https://drive.google.com/file/d/1wSoA5fm_d6JBZk4RZ1SzWLMgev4WqH21/view?usp=share_link
