### ISSUE TITLE
AttributeError: Can't pickle local object 'Diffusion.svd_based_ddnm_plus.<locals>.seed_worker'

### ISSUE THREAD

**Issue by thisissamimansour** [wyhuai/DDNM#5]
Hi. Thanks for the great job.
When running the main.py, I'm getting the mentioned error. 
Note : I'm using torch 1.8 with cuda 10.1
Please advise.

**Comment by wyhuai** [comment]
Can you show the full error info?

**Comment by huy81194tk** [comment]
![image](https://user-images.githubusercontent.com/25165106/208288769-a50fb99b-a2d1-4150-9ee2-7a37469cda06.png)
I also got the same error

**Comment by wyhuai** [comment]
> ![image](https://user-images.githubusercontent.com/25165106/208288769-a50fb99b-a2d1-4150-9ee2-7a37469cda06.png) I also got the same error

You may refer to the closed issue "i cant run the process #2"
