### ISSUE TITLE
How to calculate the Consistency metric and SSIM?

### ISSUE THREAD

**Issue by Walleclipse** [wyhuai/DDNM#53]
Thank you for your code.

I'm curious about the calculation of the Consistency metric and SSIM as reported in the paper. Would it be possible for you to provide the code for these metrics?

**Comment by wyhuai** [comment]
Hi, sorry for the late response. We use `from basicsr.metrics.psnr_ssim import calculate_ssim` to calculate SSIM. Can you provide your email? I can send you the code.

**Comment by Walleclipse** [comment]
Thank you very much. My email is abduwali54@gmail.com

**Comment by FouierL** [comment]
> Hi, sorry for the late response. We use `from basicsr.metrics.psnr_ssim import calculate_ssim` to calculate SSIM. Can you provide your email? I can send you the code.

hi, wyhuai, your work is so good and inspire me a lot.  i am a little bit confused when i calculate consistency metrics by myself, could you please send this code to me? thanks a lot for your help! my email is wuchenxu@mail.ustc.edu.cn.
